- bower.json
- firebase.html
/cc @mbleigh @rictic @e111077 
We need to make this change to address a naming conflict with the old SDK when deployed alongside the legacy firebase-element component.
> Address SDK conflict with legacy firebase-element

- firebase-auth.html
- test/firebase-auth.html
Fixes #13
@cdata I noticed that authElement.user doesn't get set right away. I'm guessing this is due to it waiting for `__authChanged` to fire.
> Fixed firebase-auth tests and issue with promises always resolving to then

- firebase-database-behavior.html
Noted that it is case-sensitive. Based docs off of: https://firebase.google.com/docs/reference/js/firebase.database.Database#ref
fixes #17 
CC: @mbleigh
> documented path property

- README.md
- firebase-query.html
The dom-repeat template examples were wrong, as they passed a value in curly brackets to the "as" attribute.
> Fixed wrong dom-repeat template example in the firebase-query element

- firebase-auth.html
This changeset adds a simple function to support `signInWithCustomToken` in the `<firebase-auth>` component.
> Fixes #35: Add <firebase-auth> support for custom token auth

- firebase-document.html
> Get stored value path fix

- firebase-document.html
Fixes #38.
Instead of removing _all_ event listeners, we remove only this instance's listeners.
> remove only this instance's listeners on detach

- firebase-common-behavior.html
- firebase-database-behavior.html
Following the [style guide](http://polymerelements.github.io/style-guide/#behaviors) this will make sure that properties and functions defined in the behaviors can be found by iron-component-page/hydrolysis and the polymer linter.
Fixes #31 and #47
> Add @polymerBehavior tags for docs and linting

- firebase-query.html
- test/firebase-query.html
Fixes (part of) #43.
When a sub-property was removed remotely, we weren't applying the change locally and were rather just adding new/existing properties only.
> apply removed sub-children on child changed

- firebase-auth.html
Just exposing the signInWithCredential method in the polymer component. 
Very useful when you already have an oauth id_token.
> Added support for signInWithCredentials

- firebase-auth.html
- test/firebase-auth.html
Fixes #23 by implementing the statusKnown property. It is set to false whenever the auth state is changed and is set to true when the user property is set. This will allow external web components to know if the user is null because firebase-auth is still initializing.
> Added statusKnown property.

- firebase-database-behavior.html
- firebase-query.html
- test/firebase-query.html
I ended up siding with a design where we just manually remove listeners in implementations that add them. Since listeners may be added to `ref`, or may be added to `query`, and since listeners require the name of the event in addition to the relevant callback to be removed, there didn't seem to be a good opportunity to generalize this cleanup.
Fixes #106
> Only remove instance-specific listeners.

- firebase-query.html
- test/firebase-query.html
Firebase Query was accidentally ignoring the second parameter to the
child_added event listener, causing newly added items (after the first
batch of add events) to be added in the wrong order.
/cc @notwaldorf
> Firebase Query ordering respects prev child key.

- bower.json
- firebase-app-script.html
- firebase-app.html
- firebase-auth-script.html
- firebase-auth.html
- firebase-common-behavior.html
- firebase-database-behavior.html
- firebase-database-script.html
- firebase-document.html
- firebase-messaging-script.html
- firebase-messaging.html
- firebase-query.html
- firebase-storage-script.html
- firebase.html
- test/firebase-common-behavior.html
- test/firebase-database-behavior.html
- test/firebase-document.html
With Firebase v3..5.1, individual JS files are now available in the Bower distribution for `firebase-{app,auth,database,messaging,storage}`.
This PR prefers using those pieces individually to encourage and enable developers to lazy-load individual components, making PolymerFire more PRPL-Compatible.
/cc @slightlyoff
> Splits imports up per-feature.

- firebase-app.html
- firebase-common-behavior.html
With the new order of element intialization (bottom-up), the
firebase-app element is typically the last one to be initialized. This
means that Polymerfire elements need to await app initialization in
order to successfully create app instances for themselves.
> Lazily await app initializing when necessary.

- README.md
Added `storage-bucket` and `messaging-sender-id` to the `README.md` to make sure people know what they are called. Issue reported on the Google Group [here](https://groups.google.com/forum/#!msg/firebase-talk/FlIIssiiKzs/qalBO7xADAAJ).
> Added `storage-bucket` and `messaging-sender-id` to docs

- firebase-query.html
Should resolve https://github.com/firebase/polymerfire/issues/100, which is a pretty serious issue.
Basically, when firebase-query path changes, the data is reset twice (`this.data = this.zeroValue`) -
- The first time here, https://github.com/firebase/polymerfire/blob/master/firebase-query.html#L287
- And the second time there,  https://github.com/firebase/polymerfire/blob/master/firebase-database-behavior.html#L95
The problem is that it happens that data is populated (via `__onFirebaseChildAdded`) before the second reset - which then clear the data Array... 
Test case : 
```html
<dom-module id="test-app">
<template>
<style>
:host {
display: block;
}
</style>
<h1>Test App</h1>
<firebase-app  api-key="AIzaSyBzKhxNa2k9pA3m9_Ji3POFAKyGGFnyshI" …
```
> Fix change path on firebase-query issue 

- firebase-database-behavior.html
- firebase-document.html
Should resolve https://github.com/firebase/polymerfire/issues/88 and https://github.com/firebase/polymerfire/issues/56.
> loop over value keys to check wich value need to be updated

- bower.json
- firebase-document.html
This is due to a Closure compiler error. `save` is a [reserved function name](https://msdn.microsoft.com/en-us/library/ms531403(v=vs.85).aspx) with a very different function signature. This has already been changed in app-storage. current bower file is correct.
Hooli bug.
> save -> saveValue

- README.md
- bower.json
Since the newly-shipped 4.1 version of the Firebase JS SDK now supports lazy loading, we no longer need to provide guidance about how to load Polymerfire. It should "just work"!
/cc @jshcrowthe
> Depend on Firebase SDK ^4.1.1, removing loading caveat.

- README.md
- bower.json
This is #213 but using a different email address, because Google's CLA office refuses to let me sign on behalf of my company.
> Speed up loading the initial data, by using the 'value' callback.

- firebase-query.html
Set removed properties to `null` instead of `undefined` so the `data` property correctly fires change notifications for them.
Fixes #248
> Fix __onFirebaseChildChanged handler

- firebase-query.html
Correct the the `__onFirebaseChildMoved` function to insert the value at the correct index
Fixes #240
> Fix child-moved handler

- bower.json
This pull requests want to make this Polymer element consistent with the majority of other Polymer elements. The uppercase version "Polymer" is closer to real name of the github project name, like presented in the git URL.
The use of mixed case does not seem to have an effect on bower and JavaScript projects. But other languages like Java are more picky and would benefit from consistency.
This pull request is a manual follow up of PolymerLabs/tedium#47 and PolymerLabs/tedium#48 which try to do this in an automated way, but are stuck.
> from polymer to Polymer

- firebase-query.html
Fixing #263
I saw that the `__queryChanged` is being called thrice, making creation of event listeners called thrice. Currently wrapped them in a checker if both `query` and `oldQuery` exists with this idea
1. `__queryChanged` is called in the `attached` phased
2. `__queryChanged` is called when any time a new `query` is created on calculated in the `__computeQuery`
Can anyone give me some feedback on any bugs I missed?
Thanks
> fix firebase query returns 2 sets for #263

- bower.json
- firebase-app.html
- firebase-firestore-script.html
Preliminary changes necessary to enable Firestore functionalities.
For now this will only allow to initalize `<firebase-app>` with the necessary `projectId` in the options and loads the script necessary to use `firebase.firestore`.
How best to implement `firebase-firestore-query` and `firebase-firestore-document` remains to be seen.
And I guess the firestore persistance option should be added to `firebase-app`?
> Prepare Firestore functionality

- firebase-firestore-mixin.html
Fixes an issue with `query` parameter being read from the constructor of an element instead of collecting the correct one from the prototype chain in FirestoreMixin.
Fixes #296
> Fix `query` in FirestoreMixin.

- firebase-firestore-mixin.html
Supersedes #294, #298, #299, #301, #303 
Resolves #283, resolves #284, resolves #287, resolves #300, resolves #302
> Multiple fixes and improvements to the FirestoreMixin

- firebase-firestore-mixin.html
> Fix persistence issue with documents, introduce noCache option, improve docs

- firebase-database-behavior.html
- firebase-document.html
- firebase-query.html
- test/firebase-document.html
- test/firebase-query.html
Replace and close https://github.com/firebase/polymerfire/pull/177. 
Follows #33 discussion. 
An "empty-result" event is fired by firebase-document or firebase-query to notify that the path does not hold any data.
> added exists attribute, reflecting whether we have data at a given path
